version: "3.9"

services:
    data-preprocessing:
        build:
          context: ./src/data_preprocessing
          dockerfile: ./Dockerfile
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/data-service-account.json
            GCP_PROJECT: "AC215-RadIQ"
    data-splitting:
        build:
          context: ./src/data_splitting
          dockerfile: ./Dockerfile
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/data-service-account.json
            GCP_PROJECT: "AC215-RadIQ"
    data-pipeline:
        build:
          context: .
          dockerfile: ./src/data_pipeline/Dockerfile
        container_name: data-pipeline
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/data-service-account.json
            GCP_PROJECT: "AC215-RadIQ"