log_to_wandb: true
sweep: true
lr: 0.001
batch_size: 16
epochs: 15
architecture: biovil
threshold: 0.0
resize: 512
ratio: 12 # importance ratio of positive to negative samples

# set to "" if you don't want to load a checkpoint
# "./ckpts/bioviL_image_4.pth"
img_ckpt: ""
txt_ckpt: ""