log_to_wandb: true
sweep: false
lr: 0.00005
batch_size: 32
epochs: 10
architecture: biovil
threshold: 0.0
resize: 512
ratio: 17 # importance ratio of positive to negative samples

# set to "" if you don't want to load a checkpoint
# "./ckpts/bioviL_image_4.pth"
img_ckpt: ""
txt_ckpt: ""
box_ckpt: ""