log_to_wandb: true
sweep: true
lr: 0.0001
batch_size: 16
epochs: 5
architecture: biovil
resize: 512
threshold: 0.0

# set to "" if you don't want to load a checkpoint
# "./ckpts/bioviL_image_4.pth"
img_ckpt: ""
txt_ckpt: ""