log_to_wandb: true
sweep: true
lr: 0.001
batch_size: 32
epochs: 20
architecture: biovil
resize: 512

# set to "" if you don't want to load a checkpoint
# "./ckpts/bioviL_image_4.pth"
img_ckpt: ""
txt_ckpt: ""